### PR TITLE
No longer overwrites the other locale when uploading a file 

### LINKED ISSUE #140: When uploading a file, the tab with the language not selected gets the same text as the one currently active
If I write "English" in the English tab and "Swedish" in the swedish tab. Then I upload a file in the Swedish tab both tabs will contain the text "Swedish + link_to_file"

### PR DESCRIPTION
**Pull request by Kalior**
Fixes #140 and enables uploading files to pages again.

I haven't actually been able to test this on posts (as I'm not currently set up to write posts), just assumed the post works the same as for pages.

### CODE REVIEW

**Comment by Vilddjur** [comment]
What if you want to add a file to only one of the locales? Or different file to the different locales?

**Comment by Kalior** [comment]
Actually haven't considered that use case. Should the upload be specific to a locale?

**Comment by Kalior** [comment]
Ah, it looks like it should be on posts but not on pages. Should perhaps handle it in the same way for both then?

**Comment by Vilddjur** [comment]
I mean that would be nice my concern is if someone is "finished" with the swedish post and switches to the english one he would accidentally add a file to the swedish one

**Comment by Kalior** [comment]
Yeah, I agree. On the other hand, it would be quite tedious to have to upload files to both locales.

**Comment by Vilddjur** [comment]
I was fiddeling with data-attributes and I think that might solve it

**Comment by Kalior** [comment]
Go ahead! Just make sure you get it working for pages as well!

**Comment by Vilddjur** [comment]
Can't get it to work, I think the issue is that we have all 4 things listening to fileuploads. This is the same problem as #139 describes. So either we need to know what actually was "targeted" and make sure only the corresponding body is filled or we have to make one fileupload listener per item.

**Pull request merged**
