### PR TITLE
Feature/banner model

### LINKED ISSUE #203: Add model for random header images
Extension of #10

### PR DESCRIPTION
**Pull request by Vilddjur**
fixes #203

### CODE REVIEW

**Comment by Vilddjur** [comment]
I would like the users to be able to like, drag and crop their selected images.
@lindskogen do you have any good ideas?

**Comment by Kalior** [comment]
Does this integrate with #217?

**Comment by Kalior** [comment]
Also, see #25, suggests the use of http://deepliquid.com/content/Jcrop.html

**Comment by Vilddjur** [comment]
Could someone check and see if they can run this locally? I had some troubles with sass/mixin transitions and had to comment all transitions out for some reason.

**Comment by Vilddjur** [comment]
Seems like the sass issues worked themselves out 🍔

**Comment by Kalior** [comment]
Would be nice if, when viewing the banners at index, users only see the banners they can edit. Also, if a committee has several banners, might be a better idea to first random committee(that has banners) and then random the banner. Otherwise, looks cool! :nail_care:

**Pull request merged**
