### PR TITLE
Change http to https on committee pages

### PR DESCRIPTION
**Pull request by Praxzy**

### CODE REVIEW

**Comment by ViddeM** [comment]
I don't know anything about ruby, but LGTM :+1:

**Comment by malmers** [comment]
Not sure why the idea stuff is included in this PR.

I like the url change of the seed file, but it's only used the first time to populate the database. To actually change the urls on ch.it you need to update the database itself.

**Comment by Praxzy** [comment]
idea-stuff as in, you want a separate PR för the idea-stuff, or that you want me to gitignore all the idea-files?

Great comment on the url-changes, I didn't know :)

**Comment by Praxzy** [comment]
Removed the idea-related stuff

**Pull request merged**
