### PR TITLE
Feature/committee index of members

### LINKED ISSUE #216: Show committee members on committee pages
We've received requests to list the committee members on the committee pages, just like on the old site. Could this be implemented via the group system perhaps by simply looping out all members for the committee?

### PR DESCRIPTION
**Pull request by Vilddjur**
Might need a designers touch before merge. @Levis92 
Also #274 needs fixing.
Closes #216

### CODE REVIEW

**Comment by Vilddjur** [comment]
Also [chalmers-account-rails#66](https://github.com/cthit/chalmersit-account-rails/issues/66) needs fixing aswell

**Comment by lindskogen** [comment]
Does this work? @Vilddjur
What is the status on merging this? @Levis92 
Would be great to have!

**Comment by Vilddjur** [comment]
Needs some design work and some issues with cacheing on bete-account but yes this PR works.

**Comment by Vilddjur** [comment]
At least on 29 of march, someone should probably test it again though 😄

**Comment by Levis92** [comment]
I'll take a look at it tonight 😃

**Comment by Kalior** [comment]
Fantastic! :dancing_men:

**Pull request merged**
