### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by jesperlindstrom**
* Show "No events today" instead of blank, if no events are displayed today.
* Added search icon to search field in the header.

### CODE REVIEW

**Comment by lindskogen** [comment]
LGTM! :)

**Comment by lindskogen** [comment]
Maybe not change the default database file?

**Comment by jesperlindstrom** [comment]
Haha whoops... why isn't that in the gitignore?

**Comment by lindskogen** [comment]
That is a good question!

**Pull request merged**
