### PR TITLE
added zh-CN locale files

### PR DESCRIPTION
**Pull request by yuxisteem**
Hi I just added zh-CN locale file(s) with Simplified Chinese translations. Let me know if there are any changes needed. Thanks.

### CODE REVIEW

**Comment by Xiaoming94** [comment]
Hello there! I am the only one in digIT who can read and understand Chinese, thus I can tell you that I am impressed by the effort. Good job!

However there are issues with including Chinese in Chalmers.it
First of all, this pull request is incomplete. Just include the standard translations alone in a locale file is not sufficient for the site to display Chinese. There are more work to be done both in the front-end and the rails backend.

Second of all. Since a great majority of the personal in the student union division that are members in our committees, and board members of the societies does not know Chinese (actually, right now, I am the only Chinese active in the division), we cannot enforce the societies and committees to translate their posts, and information to Chinese, unless you can motivate that the effort is worth it.

Don't worry, I am not rejecting this PR. I just wish that you can tell that supporting Chinese translations will benefit us in the end :)

Once again, kudos to you for your impressive effort. Keep up the good work!

**Comment by yuxisteem** [comment]
Thanks for your response. If you need more translation, pls give me a  list of files, I'm happy to help.  You may want to merge this PR is it's ok to you.

**Comment by Xiaoming94** [comment]
你是 chalmers 大学的学生吗?

**Comment by yuxisteem** [comment]
不是

**Comment by Xiaoming94** [comment]
我们会将你的PR合并到自己的一个分支里边。Thanks for your contribution :)

**Pull request merged**
