### PR TITLE
randomize header image, closes #10

### LINKED ISSUE #10: Random header image
The header image should random between student committees of the IT section.

### PR DESCRIPTION
**Pull request by Vilddjur**
An issue I am having right now is that all the images have the "faces" on different places so the position is weird for some headers. Not sure if this is solveable through the code or we will just have to ask for certain ratios for images

### CODE REVIEW

**Comment by lindskogen** [comment]
Array in ruby has a [`sample`](https://ruby-doc.org/core-2.2.0/Array.html#method-i-sample) method :)

**Comment by Vilddjur** [comment]
Nice! Thanks

**Comment by Kalior** [comment]
I kind of feel like the header images should be contained in some model, accessible only to admins or to their respective committées. Although this is a great first step.

**Comment by lindskogen** [comment]
@Vilddjur Why is this not merged yet?

**Comment by Vilddjur** [comment]
I wanted to add a model to hold the images so we wouldn't have to hard code them.

**Pull request merged**
