### PR TITLE
Fix confusing menu links

### LINKED ISSUE #157: Confusing buttons
After two years on IT, I still occasionally press the wrong button when I want to book a group room. This is because I just see "Booking" and press it, but that leads to a page for booking Hubben. I suggest to differentiate the two buttons "Booking" and "Group room" more, perhaps by using different titles or different images.

### PR DESCRIPTION
**Pull request by Kalior**
I believe this Fixes #157 can @oherik give input? Any other comments?
2016-12-06-193342_1207x163_scrot

### CODE REVIEW

**Comment by oherik** [comment]
That does make it more clear. I believe "Book Hubben" could be a viable alternative title, but that's probably too long and could look inconsistent next to simply "Group room".

**Comment by abjugard** [comment]
How about something like a banner over the Chalmers links? Or maybe a tiny Chalmers logo?

tiny-chalmers-logo

Or maybe just colouring them differently? Black for Chalmers, some shade of turquoise for IT?

it-colours

**Comment by Kalior** [comment]
I personally think the chalmers thing looks great!

**Comment by jesperlindstrom** [comment]
The Chalmers logo is a great idea. I added it like this:
skarmavbild 2016-12-07 kl 13 53 56

**Comment by Kalior** [comment]
Why is this closed instead of merged?

**Comment by jesperlindstrom** [comment]
Probably a misclick, I meant to merge. I still have the branch locally so I can check in a bit.

**Comment by Kalior** [comment]
Alright! @Edholm mentioned on the irc that maybe we aren't allowed to use Chalmers logo. Maybe we should look this up as well.

**Comment by jesperlindstrom** [comment]
@Kalior Good question. I just sent a message to the "Questions regarding use of Chalmers Logotype" email adress as listed on https://www.chalmers.se/sv/om-chalmers/profil-och-identitet/Sidor/logotyp.aspx. Also, the branch is restored haha 👍

**Comment by Kalior** [comment]
Ah, nice! Let's hope they're fine with it :dancing_men:

**Comment by jesperlindstrom** [comment]
Chalmers replied that we're allowed to use the badge on links to actual chalmers.se, but they don't want it on external services, such as TimeEdit, since that can falsely make people believe it's run by Chalmers.

I changed the icon to a graduation cap instead:

skarmavbild 2016-12-14 kl 12 16 03

**Comment by Kalior** [comment]
Okay! Looks good!

**Pull request merged**
