### PR TITLE
Fix/post navigation

### LINKED ISSUE #232: Layout issue in swedish post page
image

### PR DESCRIPTION
**Pull request by Kerp1**
Some updates to post navigation style, looks like this now, fixes #232. 

2017-02-21-211328_1203x259_scrot
2017-02-21-211305_1572x526_scrot

### CODE REVIEW

**Comment by Kalior** [comment]
I think the button "Alla nyheter" looks to be more disabled than the button "Nästa nyhet", maybe switch the two or use gray for "Nästa nyhet" and some other color for "Alla nyheter"? @jesperlindstrom advise?

**Comment by jesperlindstrom** [comment]
skarmavbild 2017-02-22 kl 08 51 32

Maybe reduce the visual "weight" of those back/forward actions, something like this... I believe the "go back to all news" will be the primary action, and going to the next/prev is secondary, so it makes sense to make the "all news" button stand out. 

I also suggest that we add left/right arrows to make it more visual... `<i class="fa fa-angle-right"></i>` or something like that. . :)

**Comment by Kalior** [comment]
Yeah, that makes a lot of sense!

**Comment by Kerp1** [comment]
If it looks like that, it makes more sense to remove the previous and next link if they don't exist right?

**Comment by jesperlindstrom** [comment]
@Kerp1 I agree :)

**Comment by Kerp1** [comment]
Changed the style as suggested and also fixed #260

**Pull request merged**
