### PR TITLE
Feature/file upload list

### LINKED ISSUE #162: Uploaded file list when crating post
A list of all uploaded files should be visible in the right or left sidebar when creating  a post.  With options to delete and possibly rename uploaded files, and getting a link to it.

### PR DESCRIPTION
**Pull request by Kerp1**
First step to making it easier to manage the files you upload when creating a post.
It currently looks like this.
image

The file link is no longer inserted automatically at caret position.
A problem with this implementation is that if the user leaves the page and goes back the files disappear.

Fixes #162

### CODE REVIEW

**Comment by NeonNeon** [comment]
I like it.
Would I get "[Sektionsmöte.pdf](/path/SektionsmöteHASH.pdf)" to the clipboard with this implementation?
A super nice thing would be if I pasted the link, the editor would select all text within the brackets so I could fast and easy change what the link should say, but I dont know if that could be implemented

**Comment by Kerp1** [comment]
I added that feature however I'm not sure if I like it or not, we can always remove it if it's more annoying than helpful.

Yes you get the same text that was previously inserted automatically in the post body.

**Comment by Vilddjur** [comment]
Would the user still drag the files to the text input? Is the file input working?

**Comment by Kerp1** [comment]
The only difference right now is that the file is added to the list on the right instead of inserted as a link in the post.

**Comment by Kalior** [comment]
Will you fix so that the uploaded files are saved together with the post in some way so that they can be displayed for editing for editing purposes this PR or is that another PR?

**Comment by lindskogen** [comment]
You can experiment with setting `mount_uploaders` on post model

**Comment by Vilddjur** [comment]
I feel like having it disconnected from post might be a good idea, since if we decide to change the uploader the files will no longer be found, this is from the behaviour of carrierwave.

**Comment by Vilddjur** [comment]
image
I'm getting translation missing, anyone else get the same?

**Comment by Kerp1** [comment]
I think you have to do something like
 ```rake assets:precompile```
Or maybe  
``` rake assets:clobber``` followed by  ```rake assets:precompile```

**Comment by Vilddjur** [comment]
That did the trick!

**Pull request merged**
