### PR TITLE
Feature/student union card balance

### LINKED ISSUE #22: Student union card balance (kårkort)
Make a signed in user enter his student union card number and show the account balance

### PR DESCRIPTION
**Pull request by Kalior**
fixes #22 
Requires phantomjs on the machine. 
Looks like this:
image
And this:
image

### CODE REVIEW

**Comment by Kalior** [comment]
It struck me that we should probably cache the balance for some time as well.

**Comment by lindskogen** [comment]
Good thinking!

**Comment by Kalior** [comment]
@lindskogen would be great if you could just look over that last commit. I think it works, but caching is confusing 😶

**Comment by lindskogen** [comment]
Looks fine!

**Pull request merged**
