### PR TITLE
Save cid after successful printer action

### LINKED ISSUE #352: Save cid on print page
This used to be the case before the migration to the new print micro-service.

### PR DESCRIPTION
**Pull request by Kalior**
Not sure if we should have a "remember me" box, but I don't feel like doing that. Fixes #352

### CODE REVIEW

**Comment by Portals** [comment]
We should have a 'Remember me' box imo, to give the user control of what data is being saved.

**Comment by Dr-Horv** [comment]
I guess this is saved in the browser? So It's actually on the user's computer rather then on our side. Giving the user full power to clear browserdata.

**Comment by Kalior** [comment]
Yeah, it's saved in LocalStorage.  And if we want to be consistent with telling the user about when we save data on their computer, we should probably consider a checkbox for saving the latest/most often used printer, as well as the student-union-card number.

**Comment by Portals** [comment]
Great, I am requesting reviews from people who I think could review this PR.

**Pull request merged**
